spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stdTable
    username: root
    password: qkdrmfdl03

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

